### ISSUE TITLE
Error when starting the game

### ISSUE THREAD

**Issue by Kpxxpkk** [Minecraft-LightLand/ModularGolems#52]
Hello. Actually, there was an error when starting the game with the addition of the golem mod. Despite the extensiveness of the assembly, everything works without it. And there is some kind of conflict with the mod "l_ender s cataclysm". Can you tell me if there is a way to fix this, or do I need to abandon one of the mods?
[crash-2024-07-15_10.18.15-fml.txt](https://github.com/user-attachments/files/16230825/crash-2024-07-15_10.18.15-fml.txt)

**Comment by lcy0x1** [comment]
You need to update Cataclysm. Cataclysm changed their code in one of their recent updates, which requires ModularGolem compat to change as well. You have the new ModularGolem version, but your Cataclysm version is still old, so that my mod is trying to access Cataclysm's new code which doesn't exist, causing crash.

Usually this is addressed by version requirement, but Cataclysm does not have their versioned builtin into their mod, I have no way to tell if they are newer version or not
