### ISSUE TITLE
1.20.1 server crash / Forge 47.3.7

### ISSUE THREAD

**Issue by Sageking10** [Minecraft-LightLand/ModularGolems#59]
I was in the nether fighting a ton of mobs when the server suddenly crashed. 
The crash log blamed this mod.
[crash-2024-09-08_22.55.13-server.txt](https://github.com/user-attachments/files/16924939/crash-2024-09-08_22.55.13-server.txt)

**Comment by lcy0x1** [comment]
This is caused by some infinite attack-thorn loop happened inside moving into a fire. The actual cause of this problem is hidden by a Forge bug.

It blames me because I modifies entity travel and the bug happens when entity travels into fire, taking damage from fire.

Join my discord if you want to have more in-depth discussion with me about how to find which mod is the culprit
